version: "3.7"

services:
  acntech.keycloak-config-cli:
    image: bitnami/keycloak-config-cli
    container_name: acntech.keycloak-config-cli
    environment:
      - KEYCLOAK_URL=http://acntech.keycloak:8080
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=abcd1234
      - KEYCLOAK_LOGINREALM=master
      - KEYCLOAK_AVAILABILITYCHECK_ENABLED=true
      - KEYCLOAK_AVAILABILITYCHECK_TIMEOUT=60s
      - IMPORT_FILES_LOCATIONS=/config/*.json
    volumes:
      - ./resources/config:/config
    networks:
      - acntech.keycloak
      - acntech.postgres

networks:
  acntech.postgres:
    name: acntech.postgres
    external: true
  acntech.keycloak:
    name: acntech.keycloak
    external: true
