### SPRING ###
spring:
  # Cloud
  cloud:
    gateway:
      routes:
        - id: ordering
          uri: http://localhost:9002
          predicates:
            - Path=/api/orders/**, /api/items/**
        - id: warehouse
          uri: http://localhost:9003
          predicates:
            - Path=/api/products/**, /api/reservations/**

### LOGGING ###
logging:
  level:
    root: INFO
    no.acntech: DEBUG

### SERVER ###
server:
  port: 9000
#  reactive:
#    session:
#      timeout: 8h
  error:
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: false
