version: '3.5'

services:
  postgres_1:
    image: postgres
    container_name: postgres_1
    environment:
      - POSTGRES_PASSWORD=aadJP1T5F50r
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
      - database:/var/lib/postgresql/data
    networks:
      - database
  kafka_1:
    image: acntechie/kafka
    container_name: kafka_1
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - ZOOKEEPER_HOSTS=zookeeper_1:2181
    depends_on:
      - zookeeper_1
    networks:
      - event_bus

  zookeeper_1:
    image: acntechie/zookeeper
    container_name: zookeeper_1
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_HOSTS=zookeeper_1:2888:3888
    networks:
      - event_bus

volumes:
  database:
    name: database

networks:
  database:
    name: database
  event_bus:
    name: event_bus
