version: '3.5'

services:
  acntech.customers.service:
    build: ./customers-service
    image: acntech/event-notification-customers-service
    container_name: acntech.customers.service
    ports:
      - "9000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - acntech.postgres
  acntech.ordering.service:
    build: ./ordering-service
    image: acntech/event-notification-ordering-service
    container_name: acntech.ordering.service
    ports:
      - "9001:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - acntech.postgres
      - acntech.kafka
  acntech.billing.service:
    build: ./billing-service
    image: acntech/event-notification-billing-service
    container_name: acntech.billing.service
    ports:
      - "9002:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - acntech.postgres
      - acntech.kafka
  acntech.shipping.service:
    build: ./shipping-service
    image: acntech/event-notification-shipping-service
    container_name: acntech.shipping.service
    ports:
      - "9003:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - acntech.postgres
      - acntech.kafka
  acntech.warehouse.service:
    build: ./warehouse-service
    image: acntech/event-notification-warehouse-service
    container_name: acntech.warehouse.service
    ports:
      - "9004:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - acntech.postgres
      - acntech.kafka

networks:
  acntech.postgres:
    name: acntech.postgres
    external: true
  acntech.kafka:
    name: acntech.kafka
    external: true
