#########################
# ACNTECH Configuration #
#########################
acntech:
  service:
    ordering:
      api:
        url: http://localhost:9010/api

########################
# SPRING Configuration #
########################
spring:
  zipkin:
    base-url: http://localhost:9411
