########################
# SPRING Configuration #
########################
spring:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  # Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://acntech.postgres:5432/warehouse
    username: warehouse
    password: abcd1234

### Management ###
management:
  # Endpoints
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - health
          - info
  # OTLP
  otlp:
    tracing:
      export:
        grpc:
          url: http://acntech.jaeger:4317

### Logging ###
logging:
  level:
    root: WARN
    no.acntech: INFO
