#########################
# ACNTECH Configuration #
#########################
acntech:
  service:
    ordering:
      url: http://acntech.ordering.service:8080

########################
# SPRING Configuration #
########################
spring:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  # Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://acntech.postgres:5432/warehouse
    username: warehouse
    password: abcd1234
  # ZipKin
  zipkin:
    base-url: http://acntech.zipkin:9411

### Logging ###
logging:
  level:
    root: WARN
    no.acntech: INFO
