### SPRING ###
spring:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:warehouse;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  # H2
  h2:
    console:
      enabled: true
  # Flyway
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata

### MANAGEMENT ###
management:
  # Endpoints
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"
  # OTLP
  otlp:
    tracing:
      export:
        grpc:
          url: http://localhost:4317

### LOGGING ###
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %-48.48c{36}){yellow} %clr(:){red} %clr(%m){faint}%n"
  level:
    root: INFO
    no.acntech: DEBUG
    io.opentelemetry: DEBUG

### SERVER ###
server:
  port: 9003
