########################
# SPRING Configuration #
########################
spring:
  profiles:
    include:
      - postgres
      - local
      - test-data
  datasource:
    url: jdbc:postgresql://localhost:5432/ordering

# Logging
logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN
    no.acntech: DEBUG
