version: "3.7"

services:
  acntech.jaeger:
    image: jaegertracing/all-in-one
    container_name: acntech.jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
    #  - "4317:4317"     # OTLP gRPC HTTP protocol
      - "4318:4318"     # OTLP JSON HTTP protocol
    #  - "5775:5775/udp" # Zipkin Thrift compact protocol
    #  - "5778:5778"
    #  - "6831:6831/udp" # Jaeger Thrift compact protocol
    #  - "6832:6832/udp" # Jaeger Thrift binary protocol
    #  - "9411:9411"     # Zipkin JSON HTTP protocol
    #  - "14250:14250"
    #  - "14268:14268"   # Jaeger Thrift direct
      - "16686:16686"   # Web UI HTTP
    volumes:
      - acntech.jaeger:/tmp
    networks:
      - acntech.jaeger

volumes:
  acntech.jaeger:
    name: acntech.jaeger

networks:
  acntech.jaeger:
    name: acntech.jaeger
