version: '3.5'

services:
  acntech.jaeger:
    image: jaegertracing/all-in-one
    container_name: acntech.jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - acntech.jaeger

networks:
  acntech.jaeger:
    name: acntech.jaeger
