version: "2.1"

services:

  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      # ui
      - "8161:8161"
      # jms
      - "61616:61616"
    environment:
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048