########################
# SPRING Configuration #
########################
spring:
  application:
    name: ui-gateway

# Logging
logging:
  level:
    root: INFO
    no.acntech: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

# Server
server:
  port: 8000
