########################
# SPRING Configuration #
########################
spring:
  profiles:
    include:
      - postgres
      - local
      - test-data

# Logging
logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN
    no.acntech: DEBUG
