#########################
# ACNTECH Configuration #
#########################
acntech:
  service:
    warehouse:
      api:
        url: http://localhost:9040/api

########################
# SPRING Configuration #
########################
