### SPRING ###
spring:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://acntech.postgres:5432/shipping
    username: shipping
    password: abcd1234
  # Kafka
  kafka:
    bootstrap-servers:
      - acntech.kafka:9092

### MANAGEMENT ###
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - health
          - info

### LOGGING ###
logging:
  level:
    root: WARN
    no.acntech: INFO
