########################
# SPRING Configuration #
########################
spring:
  application:
    name: ordering
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  jmx:
    enabled: false
  aop:
    proxy-target-class: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ordering;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true

### Security ###
security:
  # OAuth2
  oauth2:
    # Common
    issuer-uri: http://localhost:8000/auth
    authorization-server-uri: ${issuer-uri}
    # OAuth2 Client
    client:
      client-id: ordering
      client-secret: 8cb58c9a-7077-447e-984d-c8f2de428628
      user-authorization-uri: ${authorization-server-uri}/auth
      access-token-uri: ${authorization-server-uri}/token
      scope:
        - read
        - write
        - openid
      grant-type: client_credentials
    # OAuth2 Resource Server
    resource:
      id: ordering
      user-info-uri: ${authorization-server-uri}/userinfo
      token-info-uri: ${authorization-server-uri}/check_token
      jwt:
        key-value: secret

### Logging ###
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

### Server ###
server:
  port: 9010
  servlet:
    context-path: /api
