version: '3.5'

services:
  orders-service:
    image: openjdk:8-jre-alpine
      container_name: synchronous-rest-ordering-service
      ports:
        - 9010:9010
      environment:
        - SPRING_PROFILES_ACTIVE=default
      networks:
        - kafka

networks:
  kafka:
    external: true
