version: '3.5'

services:
  acntech.postgres:
    image: postgres
    container_name: acntech.postgres
    environment:
      - POSTGRES_PASSWORD=abcd1234
    ports:
      - "5432:5432"
    volumes:
      - ./resources/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
      - acntech.postgres:/var/lib/postgresql/data
    networks:
      - acntech.postgres

  acntech.kafka:
    image: acntechie/kafka
    container_name: acntech.kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - ZOOKEEPER_HOSTS=acntech.zookeeper:2181
    depends_on:
      - acntech.zookeeper
    networks:
      - acntech.kafka

  acntech.zookeeper:
    image: acntechie/zookeeper
    container_name: acntech.zookeeper
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_HOSTS=acntech.zookeeper:2888:3888
    networks:
      - acntech.kafka

  acntech.rabbitmq:
    image: rabbitmq
    container_name: acntech.rabbitmq
    ports:
      - "5672:5672"
    networks:
      - acntech.rabbitmq

  acntech.zipkin:
    image: openzipkin/zipkin
    container_name: acntech.zipkin
    ports:
      - "9411:9411"
    networks:
      - acntech.zipkin

volumes:
  acntech.postgres:
    name: acntech.postgres

networks:
  acntech.postgres:
    name: acntech.postgres
  acntech.kafka:
    name: acntech.kafka
  acntech.rabbitmq:
    name: acntech.rabbitmq
  acntech.zipkin:
    name: acntech.zipkin
