version: "3.7"

services:
  acntech.kafka:
    image: acntechie/kafka
    container_name: acntech.kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - ZOOKEEPER_HOSTS=acntech.zookeeper:2181
    depends_on:
      - acntech.zookeeper
    networks:
      - acntech.kafka

  acntech.zookeeper:
    image: acntechie/zookeeper
    container_name: acntech.zookeeper
    environment:
      - ZOOKEEPER_ID=1
      - ZOOKEEPER_HOSTS=acntech.zookeeper:2888:3888
    networks:
      - acntech.kafka

networks:
  acntech.kafka:
    name: acntech.kafka
