#########################
# ACNTECH Configuration #
#########################
acntech:
  service:
    warehouse:
      url: http://acntech.warehouse.service:8080

########################
# SPRING Configuration #
########################
spring:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  # Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://acntech.postgres:5432/ordering
    username: ordering
    password: abcd1234

### Logging ###
logging:
  level:
    root: WARN
    no.acntech: INFO
