### APP ###
app:
  service:
    warehouse:
      url: http://localhost:9003

### SPRING ###
spring:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ordering;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  # H2
  h2:
    console:
      enabled: true

### MANAGEMENT ###
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"

### RESILIENCE4J ###
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
    instances:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

### LOGGING ###
logging:
  level:
    root: INFO
    no.acntech: DEBUG

### SERVER ###
server:
  port: 9002
