#########################
# ACNTECH Configuration #
#########################
acntech:
  service:
    warehouse:
      api:
        reservations:
          url: ${acntech.service.warehouse.api.url}/reservations

########################
# SPRING Configuration #
########################
spring:
  application:
    name: circuit-breaker-ordering-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  jmx:
    enabled: false
  aop:
    proxy-target-class: true
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    locations:
      - classpath:db/vendor/${spring.datasource.platform}
      - classpath:db/migration

# Server
server:
  port: 9010
  servlet:
    context-path: /api
