version: '3.5'

services:
  shipping-service:
    image: openjdk:8-jre-alpine
      container_name: event-state-transfer-shipping-service
      ports:
        - 9030:9030
      environment:
        - SPRING_PROFILES_ACTIVE=default
      networks:
        - kafka

networks:
  kafka:
    external: true
