#########################
# ACNTECH Configuration #
#########################
acntech:
  service:
    microservice:
      api:
        reservations:
          url: ${acntech.service.warehouse.api.url}/reservations

########################
# SPRING Configuration #
########################
spring:
  application:
    name: oauth2-token-relay-ui-api
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  jmx:
    enabled: false
  aop:
    proxy-target-class: true

# Server
server:
  port: 8000
