version: '3.5'

services:
  postgres_1:
    image: postgres
    container_name: postgres_1
    environment:
      - POSTGRES_PASSWORD=aadJP1T5F50r
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
      - database:/var/lib/postgresql/data
    networks:
      - database

volumes:
  database:
    name: database

networks:
  database:
    name: database
