### APP ###
app:
  service:
    billing:
      url: http://localhost:9005
    shipping:
      url: http://localhost:9004
    warehouse:
      url: http://localhost:9003

### SPRING ###
spring:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ordering;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  # H2
  h2:
    console:
      enabled: true

### MANAGEMENT ###
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"

### LOGGING ###
logging:
  level:
    root: INFO
    no.acntech: DEBUG

### SERVER ###
server:
  port: 9002
