#########################
# ACNTECH Configuration #
#########################
acntech:
  hazelcast:
    name: ${spring.application.name}
    hosts:
      - localhost

########################
# SPRING Configuration #
########################
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ordering
          uri: http://localhost:9010
          predicates:
            - Path=/api/orders/**, /api/items/**
          filters:
            - name: StripPrefix
              args:
                parts: 1
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@rateLimiter}"
                key-resolver: "#{@keyResolver}"
                rate-limiter.limit: 3
                rate-limiter.duration: 1s
        - id: warehouse
          uri: http://localhost:9040
          predicates:
            - Path=/api/products/**, /api/reservations/**
          filters:
            - name: StripPrefix
              args:
                parts: 1
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@rateLimiter}"
                key-resolver: "#{@keyResolver}"
                rate-limiter.limit: 3
                rate-limiter.duration: 1s

### Logging ###
logging:
  level:
    root: INFO
    no.acntech: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

### Server ###
server:
  port: 8000
