### SPRING ###
spring:
  # Cloud
  cloud:
    gateway:
      routes:
        - id: ordering
          uri: http://localhost:9002
          predicates:
            - Path=/api/orders/**, /api/items/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@headerKeyResolver}"
                rate-limiter: "#{@defaultRateLimiter}"
                rate-limiter.limit: 3
                rate-limiter.duration: 1s
        - id: warehouse
          uri: http://localhost:9003
          predicates:
            - Path=/api/products/**, /api/reservations/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@headerKeyResolver}"
                rate-limiter: "#{@defaultRateLimiter}"
                rate-limiter.limit: 3
                rate-limiter.duration: 1s

### LOGGING ###
logging:
  level:
    root: INFO
    no.acntech: DEBUG

### SERVER ###
server:
  port: 9000
