### APP ###
app:
  hazelcast:
    name: ${spring.application.name}
    hosts:
      - localhost

### SPRING ###
spring:
  # Application
  application:
    name: rate-limiting-api-gateway
  # Profiles
  profiles:
    active: development
  # Cloud
  cloud:
    gateway:
      filter:
        request-rate-limiter:
          deny-empty-key: true
