version: '3.5'

services:
  billing-service:
    image: openjdk:8-jre-alpine
      container_name: syncronous-rest-billing-service
      ports:
        - 9020:9020
      environment:
        - SPRING_PROFILES_ACTIVE=default
      networks:
        - kafka

networks:
  kafka:
    external: true
