version: '3.5'

services:
  orders-service:
    image: openjdk:8-jre-alpine
      container_name: event-state-transfer-warehouse-service
      ports:
        - 9040:9040
      environment:
        - SPRING_PROFILES_ACTIVE=default
      networks:
        - kafka

networks:
  kafka:
    external: true
