########################
# SPRING Configuration #
########################
spring:
  # Security
  security:
    oauth2:
      client:
        registration:
          token-relay-ui-api:
            provider: uaa
            client-id: token-relay-ui-api
            client-secret: abcd1234
            scope:
              - openid
              - profile
              - email
        provider:
          uaa:
            issuer-uri: http://localhost:8888/uaa/oauth/token
  # Cloud
  cloud:
    gateway:
      routes:
        - id: customers
          uri: http://localhost:9001
          predicates:
            - Path=/api/customers/**
        - id: ordering
          uri: http://localhost:9002
          predicates:
            - Path=/api/orders/**, /api/items/**
        - id: warehouse
          uri: http://localhost:9003
          predicates:
            - Path=/api/products/**, /api/reservations/**

# Logging
logging:
  level:
    root: INFO
    no.acntech: DEBUG

# Server
server:
  port: 9000
