version: '3.5'

services:
  server:
    image: uaa
    build: .
    container_name: iam-server
    hostname: iam
    domainname: acntech.local
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=postgresql,default
    ports:
      - 8888:8080
    networks:
      - iam

  database:
    image: postgres
    container_name: iam-database
    hostname: database
    domainname: acntech.local
    environment:
      - POSTGRES_DB=iam
      - POSTGRES_USER=iam
      - POSTGRES_PASSWORD=hS9y05zA
    ports:
      - 5432:5432
    networks:
      - iam

networks:
  iam:
    name: iam
