#########################
# ACNTECH Configuration #
#########################
acntech:
  service:
    orders:
      url: http://localhost:9010/api/orders
    items:
      url: http://localhost:9010/api/items
    products:
      url: http://localhost:9040/api/products
    reservations:
      url: http://localhost:9040/api/reservations
  security:
    login-page: /oauth2/authorization/token-relay-ui-api
    failure-url: http://localhost:8000?error
    logout-success-url: http://localhost:8888/uaa/logout.do?client_id=token-relay-ui&redirect=http://localhost:8000

########################
# SPRING Configuration #
########################
spring:
  application:
    name: oauth2-token-relay-ui-api
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  jmx:
    enabled: false
  aop:
    proxy-target-class: true
  security:
    oauth2:
      client:
        registration:
          token-relay-ui:
            provider: uaa
            client-id: token-relay-ui
            client-secret: nzSX99Qg
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
          token-relay-ui-api:
            provider: uaa
            client-id: token-relay-ui-api
            client-secret: 0kX3bvZe
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          uaa:
            issuer-uri: http://localhost:8888/uaa/oauth/token

# Logging
logging:
  level:
    root: INFO
    no.acntech: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

# Server
server:
  port: 8000
  servlet:
    context-path: /api
