#########################
# ACNTECH Configuration #
#########################
acntech:
  service:
    warehouse:
      url: http://localhost:9003

########################
# SPRING Configuration #
########################
spring:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  # Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ordering;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  # H2
  h2:
    console:
      enabled: true

### Management ###
management:
  # Endpoints
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"
  # OTLP
#  otlp:
#    metrics:
#      export:
#        url: http://localhost:9411/v1/metrics

### Logging ###
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %-48.48c{36}){yellow} %clr(:){red} %clr(%m){faint}%n"
  level:
    root: INFO
    no.acntech: DEBUG

### Server ###
server:
  port: 9002
