########################
# SPRING Configuration #
########################
spring:
  datasource:
    url: jdbc:postgresql://ip-10-0-1-4.us-east-2.compute.internal:5432/customers

# Logging
logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN
    org.apache.kafka: WARN
    org.apache.kafka.clients.admin.AdminClientConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.streams.StreamsConfig: WARN
    no.acntech: DEBUG

# Server
server:
  port: 9000
  servlet:
    context-path: /api
