########################
# SPRING Configuration #
########################
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    platform: oracle
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:customers;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true

# Logging
logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN
    org.apache.kafka: WARN
    org.apache.kafka.clients.admin.AdminClientConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.streams.StreamsConfig: WARN
    no.acntech: DEBUG

# Server
server:
  port: 9000
  servlet:
    context-path: /api
