########################
# SPRING Configuration #
########################
spring:
  profiles:
    include:
      - h2
      - default

# Logging
logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN
    org.apache.kafka: WARN
    org.apache.kafka.clients.admin.AdminClientConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.streams.StreamsConfig: WARN
    no.acntech: DEBUG

# Server
server:
  port: 9000
  servlet:
    context-path: /api
