########################
# SPRING Configuration #
########################
spring:
  application:
    name: customer
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
  jmx:
    enabled: false
  aop:
    proxy-target-class: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true

# Logging
logging:
  level:
    org.springframework: INFO
    no.acntech: DEBUG

# Server
server:
  port: 9000
  servlet:
    context-path: /api
