#########################
# ACNTECH Configuration #
#########################
acntech:
  service:
    warehouse:
      api:
        url: http://internal-j2c-p1-elb-private-http-56999450.us-east-2.elb.amazonaws.com/warehouse/api

########################
# SPRING Configuration #
########################
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ip-10-0-1-4.us-east-2.compute.internal:5432/ordering
    username: ordering
    password: 7f15MUKYFRtb
  kafka:
    bootstrap-servers:
      - ip-10-0-1-91.us-east-2.compute.internal:9092

# Logging
logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN
    org.apache.kafka: WARN
    org.apache.kafka.clients.admin.AdminClientConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.streams.StreamsConfig: WARN
    no.acntech: DEBUG

# Server
server:
  port: 9010
  servlet:
    context-path: /ordering/api
