#########################
# ACNTECH Configuration #
#########################
acntech:
  service:
    warehouse:
      api:
        url: http://localhost:9040/api

########################
# SPRING Configuration #
########################
spring:
  profiles:
    include:
      - postgres
      - default
  kafka:
    bootstrap-servers:
      - localhost:9092

# Logging
logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN
    org.apache.kafka: WARN
    org.apache.kafka.clients.admin.AdminClientConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.streams.StreamsConfig: WARN
    no.acntech: DEBUG

# Server
server:
  port: 9010
  servlet:
    context-path: /api
